### ISSUE TITLE
Show PSU information

### ISSUE THREAD

**Issue by gravitystorm** [osmfoundation/osmf-server-info#10]
We've found a need for showing whether the machines are dual powered or only singly powered. Is it possible to find out if a) there are 2 psus and b) the power status (on/off) of each PSU?

**Comment by tomhughes** [comment]
I think we already enumerate the PSUs? I doubt there is any way to tell if they are powered though, except on those machines with IPMI power monitoring support.

**Comment by Firefishy** [comment]
On HP systems you can get the power status via: `hpasmcli -s 'show powersupply'` or `hplog -p`

**Comment by tomhughes** [comment]
Turns out there was a bug that was preventing PSU data being collected on most machines but https://github.com/openstreetmap/chef/commit/87774170bfd5acc624344a503d9bbcc1e88354ba has fixed it.

All the HP machines should now be reporting, and some of the others.

The web interface shows the PSUs but not whether they are plugged in but so far everything seems to be.

**Comment by pnorman** [comment]
The hardware is shown on hardware.osm.org now, and the status can be viewed through prometheus. All our servers (except possibly Raspberry Pi OOBs) have dual power supplies now
